name: Deploy

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.27
      - run: bun install --frozen-lockfile
      - run: npx just web-publish
        env:
          OMG_KEY: ${{ secrets.OMG_KEY }}
