name: Preview

on:
  pull_request:
    branches:
      - main

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.27
      - run: bun install --frozen-lockfile
      - run: npx just web-preview
        env:
          OMG_KEY: ${{ secrets.OMG_KEY }}
      - run: "echo 'Preview URL: https://home.omg.lol/address/brock/web/preview'"

  weblog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.27
      - run: bun install --frozen-lockfile
      - run: npx just weblog-preview
        env:
          OMG_KEY: ${{ secrets.OMG_KEY }}
