name: Preview

on:
  pull_request:
    branches:
      - main

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.27
      - run: bun install --frozen-lockfile
      - run: bunx just web-preview
        env:
          OMG_KEY: ${{ secrets.OMG_KEY }}

  weblog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.27
      - run: bun install --frozen-lockfile
      - run: bunx just weblog-preview ${{ github.event.pull_request.base.sha }} ${{ github.sha }}
        env:
          OMG_KEY: ${{ secrets.OMG_KEY }}
