name: Publish

on:
  pull_request:
    types:
      - closed

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.27
      - run: bun install --frozen-lockfile
      - run: bunx just web-publish
        env:
          OMG_KEY: ${{ secrets.OMG_KEY }}

  weblog:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.27
      - run: bun install --frozen-lockfile
      - run: bunx just weblog-publish ${{ github.event.pull_request.base.sha }} ${{ github.sha }}
        env:
          OMG_KEY: ${{ secrets.OMG_KEY }}
          DEBUG: simple-git
