name: Publish

on:
  pull_request:
    types:
      - closed

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.27
      - run: bun install --frozen-lockfile
      - run: npx just web-publish
        env:
          OMG_KEY: ${{ secrets.OMG_KEY }}

  weblog:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.27
      - run: bun install --frozen-lockfile
      - id: changed-files
        uses: tj-actions/changed-files@e9772d140489982e0e3704fea5ee93d536f1e275 #v45.0.1
        with:
          files: weblog/*/**
      - run: npx just weblog-publish ${CHANGED_FILES}
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          OMG_KEY: ${{ secrets.OMG_KEY }}
